### ISSUE TITLE
[fix] Dash confusion in data.json

### ISSUE THREAD

**Issue by joebowbeer** [ladjs/country-language#1]
## Describe the bug

vscode displays numerous warnings regarding the presence of _en dashes_ in place of _hyphens_

> The character U+2013 "–" could be confused with the character U+002d "-", which is more common in source code

## Code to reproduce

https://github.dev/ladjs/country-language/blob/master/data.json

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.
- [ ] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by titanism** [comment]
PR welcome if you'd like to fix

**Comment by joebowbeer** [comment]
Not a bug: https://github.com/ladjs/country-language/pull/4#issuecomment-1190783628
