### ISSUE TITLE
[fix] Invalid character in Provençal

### ISSUE THREAD

**Issue by joebowbeer** [ladjs/country-language#2]
## Describe the bug

Invalid `ç` in Provençal at line 7219

https://github.com/ladjs/country-language/blob/master/data.json#L7219

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.
- [ ] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by titanism** [comment]
PR welcome if you'd like to fix
