### ISSUE TITLE
Add support for typescript

### ISSUE THREAD

**Issue by jmmwangi007** [ladjs/country-language#8]
## Describe the feature

I cannot fined types for this package. I want to use it in a typescript website. Any idea where i can find the types?

This is the error i get:

       djs/country-language'. 'D:/deploy/node_modules/@ladjs/country-language/index.js' implicitly has an 'any' type.
       Try `npm i --save-dev @types/ladjs__country-language` if it exists or add a new declaration (.d.ts) file containing `declare module 
      '@ladjs/country-language';`

## Checklist

✅ I have searched through GitHub issues for similar issues.
✅ I have completely read through the README and documentation.

**Comment by titanism** [comment]
TypeScript is garbage and we do not support it
